### ISSUE TITLE
Where should i insert each pin without I2C interface?

### ISSUE THREAD

**Issue by pandailing** [Bill2462/MPU9255-Arduino-Library#16]
well, i only know a few pin like
VCC (imu sensor) -> 5v (arduino)
GND (imu sensor) -> GND (arduino)

but i still dont know where to insert
SDA
SCA
INT
FSYNC

please give more info about it, thank you

**Comment by Bill2462** [comment]
SDA (data line) and SCL (clock line) should be connected to the I2C interface of your arduino board. 
SDA (imu) -> SDA (arduino)
SCL (imu) -> SCL (arduino)
But be careful because some MPU9255 modules don't support 5V  (in this case you should plug 3.3V to VCC and use logic level converter for SCL SDA and INT pin). 

If you don't want to use interrupts then you can leave INT (interrupt output) pin unconnected. 
FSCYNC pin is currently not supported by library so leave it unconnected.
